<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.BezierControl</code>
 */
class BezierControl extends Message
{
    /**
     * Generated from protobuf field <code>optional .editor.Point2D control_in = 1;</code>
     */
    protected $control_in = null;

    /**
     * Generated from protobuf field <code>optional .editor.Point2D control_out = 2;</code>
     */
    protected $control_out = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type \Editor\Point2D $control_in
     * @type \Editor\Point2D $control_out
     *                       }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .editor.Point2D control_in = 1;</code>
     *
     * @return Point2D|null
     */
    public function getControlIn()
    {
        return $this->control_in;
    }

    public function hasControlIn()
    {
        return isset($this->control_in);
    }

    public function clearControlIn()
    {
        unset($this->control_in);
    }

    /**
     * Generated from protobuf field <code>optional .editor.Point2D control_in = 1;</code>
     *
     * @param  Point2D  $var
     * @return $this
     */
    public function setControlIn($var)
    {
        GPBUtil::checkMessage($var, Point2D::class);
        $this->control_in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .editor.Point2D control_out = 2;</code>
     *
     * @return Point2D|null
     */
    public function getControlOut()
    {
        return $this->control_out;
    }

    public function hasControlOut()
    {
        return isset($this->control_out);
    }

    public function clearControlOut()
    {
        unset($this->control_out);
    }

    /**
     * Generated from protobuf field <code>optional .editor.Point2D control_out = 2;</code>
     *
     * @param  Point2D  $var
     * @return $this
     */
    public function setControlOut($var)
    {
        GPBUtil::checkMessage($var, Point2D::class);
        $this->control_out = $var;

        return $this;
    }
}
