<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.CanvasDefinition</code>
 */
class CanvasDefinition extends Message
{
    /**
     * Generated from protobuf field <code>double width = 1;</code>
     */
    protected $width = 0.0;

    /**
     * Generated from protobuf field <code>double height = 2;</code>
     */
    protected $height = 0.0;

    /**
     * Generated from protobuf field <code>int32 background_color = 3;</code>
     */
    protected $background_color = 0;

    /**
     * Generated from protobuf field <code>bool grid_enabled = 4;</code>
     */
    protected $grid_enabled = false;

    /**
     * Generated from protobuf field <code>double grid_spacing = 5;</code>
     */
    protected $grid_spacing = 0.0;

    /**
     * Generated from protobuf field <code>bool snap_enabled = 6;</code>
     */
    protected $snap_enabled = false;

    /**
     * Generated from protobuf field <code>string unit = 7;</code>
     */
    protected $unit = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type float $width
     * @type float $height
     * @type int $background_color
     * @type bool $grid_enabled
     * @type float $grid_spacing
     * @type bool $snap_enabled
     * @type string $unit
     *              }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double width = 1;</code>
     *
     * @return float
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>double width = 1;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double height = 2;</code>
     *
     * @return float
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>double height = 2;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 background_color = 3;</code>
     *
     * @return int
     */
    public function getBackgroundColor()
    {
        return $this->background_color;
    }

    /**
     * Generated from protobuf field <code>int32 background_color = 3;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setBackgroundColor($var)
    {
        GPBUtil::checkInt32($var);
        $this->background_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool grid_enabled = 4;</code>
     *
     * @return bool
     */
    public function getGridEnabled()
    {
        return $this->grid_enabled;
    }

    /**
     * Generated from protobuf field <code>bool grid_enabled = 4;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setGridEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->grid_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double grid_spacing = 5;</code>
     *
     * @return float
     */
    public function getGridSpacing()
    {
        return $this->grid_spacing;
    }

    /**
     * Generated from protobuf field <code>double grid_spacing = 5;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setGridSpacing($var)
    {
        GPBUtil::checkDouble($var);
        $this->grid_spacing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool snap_enabled = 6;</code>
     *
     * @return bool
     */
    public function getSnapEnabled()
    {
        return $this->snap_enabled;
    }

    /**
     * Generated from protobuf field <code>bool snap_enabled = 6;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setSnapEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->snap_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit = 7;</code>
     *
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 7;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, true);
        $this->unit = $var;

        return $this;
    }
}
