<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\MapField;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.ChangelogEntry</code>
 */
class ChangelogEntry extends Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';

    /**
     * Generated from protobuf field <code>int64 created_at = 2;</code>
     */
    protected $created_at = 0;

    /**
     * Generated from protobuf field <code>string summary = 3;</code>
     */
    protected $summary = '';

    /**
     * Generated from protobuf field <code>map<string, double> measure_snapshot = 4;</code>
     */
    private $measure_snapshot;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $version
     * @type int|string $created_at
     * @type string $summary
     * @type array|\Google\Protobuf\Internal\MapField $measure_snapshot
     *                                                }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 2;</code>
     *
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 2;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string summary = 3;</code>
     *
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>string summary = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, true);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, double> measure_snapshot = 4;</code>
     *
     * @return MapField
     */
    public function getMeasureSnapshot()
    {
        return $this->measure_snapshot;
    }

    /**
     * Generated from protobuf field <code>map<string, double> measure_snapshot = 4;</code>
     *
     * @param  array|MapField  $var
     * @return $this
     */
    public function setMeasureSnapshot($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::DOUBLE);
        $this->measure_snapshot = $arr;

        return $this;
    }
}
