<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.Color</code>
 */
class Color extends Message
{
    /**
     * Generated from protobuf field <code>int32 argb = 1;</code>
     */
    protected $argb = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $argb
     *           }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 argb = 1;</code>
     *
     * @return int
     */
    public function getArgb()
    {
        return $this->argb;
    }

    /**
     * Generated from protobuf field <code>int32 argb = 1;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setArgb($var)
    {
        GPBUtil::checkInt32($var);
        $this->argb = $var;

        return $this;
    }
}
