<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.Document</code>
 */
class Document extends Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Generated from protobuf field <code>int32 schema_version = 2;</code>
     */
    protected $schema_version = 0;

    /**
     * Generated from protobuf field <code>string kind = 3;</code>
     */
    protected $kind = '';

    /**
     * Generated from protobuf field <code>.editor.CanvasDefinition canvas = 4;</code>
     */
    protected $canvas = null;

    /**
     * Generated from protobuf field <code>repeated .editor.Layer layers = 5;</code>
     */
    private $layers;

    /**
     * Generated from protobuf field <code>repeated .editor.UnifiedNode nodes = 6;</code>
     */
    private $nodes;

    /**
     * Generated from protobuf field <code>int32 revision = 7;</code>
     */
    protected $revision = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $id
     * @type int $schema_version
     * @type string $kind
     * @type \Editor\CanvasDefinition $canvas
     * @type array<\Editor\Layer>|\Google\Protobuf\Internal\RepeatedField $layers
     * @type array<\Editor\UnifiedNode>|\Google\Protobuf\Internal\RepeatedField $nodes
     * @type int $revision
     *           }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 schema_version = 2;</code>
     *
     * @return int
     */
    public function getSchemaVersion()
    {
        return $this->schema_version;
    }

    /**
     * Generated from protobuf field <code>int32 schema_version = 2;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setSchemaVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->schema_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 3;</code>
     *
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkString($var, true);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.CanvasDefinition canvas = 4;</code>
     *
     * @return CanvasDefinition|null
     */
    public function getCanvas()
    {
        return $this->canvas;
    }

    public function hasCanvas()
    {
        return isset($this->canvas);
    }

    public function clearCanvas()
    {
        unset($this->canvas);
    }

    /**
     * Generated from protobuf field <code>.editor.CanvasDefinition canvas = 4;</code>
     *
     * @param  CanvasDefinition  $var
     * @return $this
     */
    public function setCanvas($var)
    {
        GPBUtil::checkMessage($var, CanvasDefinition::class);
        $this->canvas = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.Layer layers = 5;</code>
     *
     * @return RepeatedField
     */
    public function getLayers()
    {
        return $this->layers;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.Layer layers = 5;</code>
     *
     * @param  array<Layer>|RepeatedField  $var
     * @return $this
     */
    public function setLayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Layer::class);
        $this->layers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.UnifiedNode nodes = 6;</code>
     *
     * @return RepeatedField
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.UnifiedNode nodes = 6;</code>
     *
     * @param  array<UnifiedNode>|RepeatedField  $var
     * @return $this
     */
    public function setNodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, UnifiedNode::class);
        $this->nodes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 revision = 7;</code>
     *
     * @return int
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>int32 revision = 7;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt32($var);
        $this->revision = $var;

        return $this;
    }
}
