<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.EditorProject</code>
 */
class EditorProject extends Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Generated from protobuf field <code>int32 schema_version = 3;</code>
     */
    protected $schema_version = 0;

    /**
     * Generated from protobuf field <code>string project_type = 4;</code>
     */
    protected $project_type = '';

    /**
     * Generated from protobuf field <code>int64 created_at = 5;</code>
     */
    protected $created_at = 0;

    /**
     * Generated from protobuf field <code>int64 updated_at = 6;</code>
     */
    protected $updated_at = 0;

    /**
     * Generated from protobuf field <code>optional int64 last_opened_at = 7;</code>
     */
    protected $last_opened_at = null;

    /**
     * Generated from protobuf field <code>optional string linked_model_external_id = 8;</code>
     */
    protected $linked_model_external_id = null;

    /**
     * Generated from protobuf field <code>optional string linked_pattern_external_id = 9;</code>
     */
    protected $linked_pattern_external_id = null;

    /**
     * Generated from protobuf field <code>.editor.Document document = 10;</code>
     */
    protected $document = null;

    /**
     * Generated from protobuf field <code>optional .editor.PatternProjectData pattern_data = 11;</code>
     */
    protected $pattern_data = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $id
     * @type string $name
     * @type int $schema_version
     * @type string $project_type
     * @type int|string $created_at
     * @type int|string $updated_at
     * @type int|string $last_opened_at
     * @type string $linked_model_external_id
     * @type string $linked_pattern_external_id
     * @type \Editor\Document $document
     * @type \Editor\PatternProjectData $pattern_data
     *                                  }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 schema_version = 3;</code>
     *
     * @return int
     */
    public function getSchemaVersion()
    {
        return $this->schema_version;
    }

    /**
     * Generated from protobuf field <code>int32 schema_version = 3;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setSchemaVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->schema_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string project_type = 4;</code>
     *
     * @return string
     */
    public function getProjectType()
    {
        return $this->project_type;
    }

    /**
     * Generated from protobuf field <code>string project_type = 4;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setProjectType($var)
    {
        GPBUtil::checkString($var, true);
        $this->project_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 5;</code>
     *
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 5;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 6;</code>
     *
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 6;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 last_opened_at = 7;</code>
     *
     * @return int|string
     */
    public function getLastOpenedAt()
    {
        return isset($this->last_opened_at) ? $this->last_opened_at : 0;
    }

    public function hasLastOpenedAt()
    {
        return isset($this->last_opened_at);
    }

    public function clearLastOpenedAt()
    {
        unset($this->last_opened_at);
    }

    /**
     * Generated from protobuf field <code>optional int64 last_opened_at = 7;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setLastOpenedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_opened_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string linked_model_external_id = 8;</code>
     *
     * @return string
     */
    public function getLinkedModelExternalId()
    {
        return isset($this->linked_model_external_id) ? $this->linked_model_external_id : '';
    }

    public function hasLinkedModelExternalId()
    {
        return isset($this->linked_model_external_id);
    }

    public function clearLinkedModelExternalId()
    {
        unset($this->linked_model_external_id);
    }

    /**
     * Generated from protobuf field <code>optional string linked_model_external_id = 8;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setLinkedModelExternalId($var)
    {
        GPBUtil::checkString($var, true);
        $this->linked_model_external_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string linked_pattern_external_id = 9;</code>
     *
     * @return string
     */
    public function getLinkedPatternExternalId()
    {
        return isset($this->linked_pattern_external_id) ? $this->linked_pattern_external_id : '';
    }

    public function hasLinkedPatternExternalId()
    {
        return isset($this->linked_pattern_external_id);
    }

    public function clearLinkedPatternExternalId()
    {
        unset($this->linked_pattern_external_id);
    }

    /**
     * Generated from protobuf field <code>optional string linked_pattern_external_id = 9;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setLinkedPatternExternalId($var)
    {
        GPBUtil::checkString($var, true);
        $this->linked_pattern_external_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.Document document = 10;</code>
     *
     * @return Document|null
     */
    public function getDocument()
    {
        return $this->document;
    }

    public function hasDocument()
    {
        return isset($this->document);
    }

    public function clearDocument()
    {
        unset($this->document);
    }

    /**
     * Generated from protobuf field <code>.editor.Document document = 10;</code>
     *
     * @param  Document  $var
     * @return $this
     */
    public function setDocument($var)
    {
        GPBUtil::checkMessage($var, Document::class);
        $this->document = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .editor.PatternProjectData pattern_data = 11;</code>
     *
     * @return PatternProjectData|null
     */
    public function getPatternData()
    {
        return $this->pattern_data;
    }

    public function hasPatternData()
    {
        return isset($this->pattern_data);
    }

    public function clearPatternData()
    {
        unset($this->pattern_data);
    }

    /**
     * Generated from protobuf field <code>optional .editor.PatternProjectData pattern_data = 11;</code>
     *
     * @param  PatternProjectData  $var
     * @return $this
     */
    public function setPatternData($var)
    {
        GPBUtil::checkMessage($var, PatternProjectData::class);
        $this->pattern_data = $var;

        return $this;
    }
}
