<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.FabricProperties</code>
 */
class FabricProperties extends Message
{
    /**
     * Generated from protobuf field <code>int32 cut_count = 1;</code>
     */
    protected $cut_count = 0;

    /**
     * Generated from protobuf field <code>double fabric_direction = 2;</code>
     */
    protected $fabric_direction = 0.0;

    /**
     * Generated from protobuf field <code>string fabric_type = 3;</code>
     */
    protected $fabric_type = '';

    /**
     * Generated from protobuf field <code>double fabric_meters = 4;</code>
     */
    protected $fabric_meters = 0.0;

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     */
    protected $notes = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $cut_count
     * @type float $fabric_direction
     * @type string $fabric_type
     * @type float $fabric_meters
     * @type string $notes
     *              }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 cut_count = 1;</code>
     *
     * @return int
     */
    public function getCutCount()
    {
        return $this->cut_count;
    }

    /**
     * Generated from protobuf field <code>int32 cut_count = 1;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setCutCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->cut_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double fabric_direction = 2;</code>
     *
     * @return float
     */
    public function getFabricDirection()
    {
        return $this->fabric_direction;
    }

    /**
     * Generated from protobuf field <code>double fabric_direction = 2;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setFabricDirection($var)
    {
        GPBUtil::checkDouble($var);
        $this->fabric_direction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fabric_type = 3;</code>
     *
     * @return string
     */
    public function getFabricType()
    {
        return $this->fabric_type;
    }

    /**
     * Generated from protobuf field <code>string fabric_type = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setFabricType($var)
    {
        GPBUtil::checkString($var, true);
        $this->fabric_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double fabric_meters = 4;</code>
     *
     * @return float
     */
    public function getFabricMeters()
    {
        return $this->fabric_meters;
    }

    /**
     * Generated from protobuf field <code>double fabric_meters = 4;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setFabricMeters($var)
    {
        GPBUtil::checkDouble($var);
        $this->fabric_meters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, true);
        $this->notes = $var;

        return $this;
    }
}
