<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.Layer</code>
 */
class Layer extends Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Generated from protobuf field <code>int32 z_index = 3;</code>
     */
    protected $z_index = 0;

    /**
     * Generated from protobuf field <code>bool visible = 4;</code>
     */
    protected $visible = false;

    /**
     * Generated from protobuf field <code>bool locked = 5;</code>
     */
    protected $locked = false;

    /**
     * Generated from protobuf field <code>double opacity = 6;</code>
     */
    protected $opacity = 0.0;

    /**
     * Generated from protobuf field <code>optional string group_id = 7;</code>
     */
    protected $group_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $id
     * @type string $name
     * @type int $z_index
     * @type bool $visible
     * @type bool $locked
     * @type float $opacity
     * @type string $group_id
     *              }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 z_index = 3;</code>
     *
     * @return int
     */
    public function getZIndex()
    {
        return $this->z_index;
    }

    /**
     * Generated from protobuf field <code>int32 z_index = 3;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setZIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->z_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool visible = 4;</code>
     *
     * @return bool
     */
    public function getVisible()
    {
        return $this->visible;
    }

    /**
     * Generated from protobuf field <code>bool visible = 4;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setVisible($var)
    {
        GPBUtil::checkBool($var);
        $this->visible = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool locked = 5;</code>
     *
     * @return bool
     */
    public function getLocked()
    {
        return $this->locked;
    }

    /**
     * Generated from protobuf field <code>bool locked = 5;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->locked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double opacity = 6;</code>
     *
     * @return float
     */
    public function getOpacity()
    {
        return $this->opacity;
    }

    /**
     * Generated from protobuf field <code>double opacity = 6;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setOpacity($var)
    {
        GPBUtil::checkDouble($var);
        $this->opacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string group_id = 7;</code>
     *
     * @return string
     */
    public function getGroupId()
    {
        return isset($this->group_id) ? $this->group_id : '';
    }

    public function hasGroupId()
    {
        return isset($this->group_id);
    }

    public function clearGroupId()
    {
        unset($this->group_id);
    }

    /**
     * Generated from protobuf field <code>optional string group_id = 7;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, true);
        $this->group_id = $var;

        return $this;
    }
}
