<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use UnexpectedValueException;

/**
 * Protobuf type <code>editor.NodeCategory</code>
 */
class NodeCategory
{
    /**
     * Generated from protobuf enum <code>CATEGORY_GENERIC = 0;</code>
     */
    const CATEGORY_GENERIC = 0;

    /**
     * Generated from protobuf enum <code>CATEGORY_BODICE_FRONT = 1;</code>
     */
    const CATEGORY_BODICE_FRONT = 1;

    /**
     * Generated from protobuf enum <code>CATEGORY_BODICE_BACK = 2;</code>
     */
    const CATEGORY_BODICE_BACK = 2;

    /**
     * Generated from protobuf enum <code>CATEGORY_SLEEVE = 3;</code>
     */
    const CATEGORY_SLEEVE = 3;

    /**
     * Generated from protobuf enum <code>CATEGORY_COLLAR = 4;</code>
     */
    const CATEGORY_COLLAR = 4;

    /**
     * Generated from protobuf enum <code>CATEGORY_CUFF = 5;</code>
     */
    const CATEGORY_CUFF = 5;

    /**
     * Generated from protobuf enum <code>CATEGORY_POCKET = 6;</code>
     */
    const CATEGORY_POCKET = 6;

    /**
     * Generated from protobuf enum <code>CATEGORY_WAISTBAND = 7;</code>
     */
    const CATEGORY_WAISTBAND = 7;

    /**
     * Generated from protobuf enum <code>CATEGORY_PANEL = 8;</code>
     */
    const CATEGORY_PANEL = 8;

    /**
     * Generated from protobuf enum <code>CATEGORY_ANNOTATION = 9;</code>
     */
    const CATEGORY_ANNOTATION = 9;

    /**
     * Generated from protobuf enum <code>CATEGORY_LINING = 10;</code>
     */
    const CATEGORY_LINING = 10;

    /**
     * Generated from protobuf enum <code>CATEGORY_HOOD = 11;</code>
     */
    const CATEGORY_HOOD = 11;

    /**
     * Generated from protobuf enum <code>CATEGORY_LEG = 12;</code>
     */
    const CATEGORY_LEG = 12;

    private static $valueToName = [
        self::CATEGORY_GENERIC => 'CATEGORY_GENERIC',
        self::CATEGORY_BODICE_FRONT => 'CATEGORY_BODICE_FRONT',
        self::CATEGORY_BODICE_BACK => 'CATEGORY_BODICE_BACK',
        self::CATEGORY_SLEEVE => 'CATEGORY_SLEEVE',
        self::CATEGORY_COLLAR => 'CATEGORY_COLLAR',
        self::CATEGORY_CUFF => 'CATEGORY_CUFF',
        self::CATEGORY_POCKET => 'CATEGORY_POCKET',
        self::CATEGORY_WAISTBAND => 'CATEGORY_WAISTBAND',
        self::CATEGORY_PANEL => 'CATEGORY_PANEL',
        self::CATEGORY_ANNOTATION => 'CATEGORY_ANNOTATION',
        self::CATEGORY_LINING => 'CATEGORY_LINING',
        self::CATEGORY_HOOD => 'CATEGORY_HOOD',
        self::CATEGORY_LEG => 'CATEGORY_LEG',
    ];

    public static function name($value)
    {
        if (! isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (! defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
