<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use UnexpectedValueException;

/**
 * Protobuf type <code>editor.NodeType</code>
 */
class NodeType
{
    /**
     * Generated from protobuf enum <code>TYPE_PATH = 0;</code>
     */
    const TYPE_PATH = 0;

    /**
     * Generated from protobuf enum <code>TYPE_LINE = 1;</code>
     */
    const TYPE_LINE = 1;

    /**
     * Generated from protobuf enum <code>TYPE_RECTANGLE = 2;</code>
     */
    const TYPE_RECTANGLE = 2;

    /**
     * Generated from protobuf enum <code>TYPE_ELLIPSE = 3;</code>
     */
    const TYPE_ELLIPSE = 3;

    /**
     * Generated from protobuf enum <code>TYPE_TEXT = 4;</code>
     */
    const TYPE_TEXT = 4;

    /**
     * Generated from protobuf enum <code>TYPE_ANNOTATION = 5;</code>
     */
    const TYPE_ANNOTATION = 5;

    private static $valueToName = [
        self::TYPE_PATH => 'TYPE_PATH',
        self::TYPE_LINE => 'TYPE_LINE',
        self::TYPE_RECTANGLE => 'TYPE_RECTANGLE',
        self::TYPE_ELLIPSE => 'TYPE_ELLIPSE',
        self::TYPE_TEXT => 'TYPE_TEXT',
        self::TYPE_ANNOTATION => 'TYPE_ANNOTATION',
    ];

    public static function name($value)
    {
        if (! isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (! defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
