<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.PathCommand</code>
 */
class PathCommand extends Message
{
    /**
     * Generated from protobuf field <code>.editor.PathCommandType type = 1;</code>
     */
    protected $type = 0;

    /**
     * Generated from protobuf field <code>repeated .editor.Point2D points = 2;</code>
     */
    private $points;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $type
     * @type array<\Editor\Point2D>|\Google\Protobuf\Internal\RepeatedField $points
     *                                                                      }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.editor.PathCommandType type = 1;</code>
     *
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.editor.PathCommandType type = 1;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, PathCommandType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.Point2D points = 2;</code>
     *
     * @return RepeatedField
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.Point2D points = 2;</code>
     *
     * @param  array<Point2D>|RepeatedField  $var
     * @return $this
     */
    public function setPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Point2D::class);
        $this->points = $arr;

        return $this;
    }
}
