<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use UnexpectedValueException;

/**
 * Protobuf type <code>editor.PathCommandType</code>
 */
class PathCommandType
{
    /**
     * Generated from protobuf enum <code>PATH_MOVE_TO = 0;</code>
     */
    const PATH_MOVE_TO = 0;

    /**
     * Generated from protobuf enum <code>PATH_LINE_TO = 1;</code>
     */
    const PATH_LINE_TO = 1;

    /**
     * Generated from protobuf enum <code>PATH_CUBIC_TO = 2;</code>
     */
    const PATH_CUBIC_TO = 2;

    private static $valueToName = [
        self::PATH_MOVE_TO => 'PATH_MOVE_TO',
        self::PATH_LINE_TO => 'PATH_LINE_TO',
        self::PATH_CUBIC_TO => 'PATH_CUBIC_TO',
    ];

    public static function name($value)
    {
        if (! isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (! defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
