<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\MapField;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.PatternProjectData</code>
 */
class PatternProjectData extends Message
{
    /**
     * Generated from protobuf field <code>string pattern_id = 1;</code>
     */
    protected $pattern_id = '';

    /**
     * Generated from protobuf field <code>string pattern_name = 2;</code>
     */
    protected $pattern_name = '';

    /**
     * Generated from protobuf field <code>string model_external_id = 3;</code>
     */
    protected $model_external_id = '';

    /**
     * Generated from protobuf field <code>string model_name = 4;</code>
     */
    protected $model_name = '';

    /**
     * Generated from protobuf field <code>string version = 5;</code>
     */
    protected $version = '';

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     */
    protected $method = '';

    /**
     * Generated from protobuf field <code>map<string, double> measure_refs = 7;</code>
     */
    private $measure_refs;

    /**
     * Generated from protobuf field <code>repeated .editor.ChangelogEntry changelogs = 8;</code>
     */
    private $changelogs;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $pattern_id
     * @type string $pattern_name
     * @type string $model_external_id
     * @type string $model_name
     * @type string $version
     * @type string $method
     * @type array|\Google\Protobuf\Internal\MapField $measure_refs
     * @type array<\Editor\ChangelogEntry>|\Google\Protobuf\Internal\RepeatedField $changelogs
     *                                                                             }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string pattern_id = 1;</code>
     *
     * @return string
     */
    public function getPatternId()
    {
        return $this->pattern_id;
    }

    /**
     * Generated from protobuf field <code>string pattern_id = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setPatternId($var)
    {
        GPBUtil::checkString($var, true);
        $this->pattern_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pattern_name = 2;</code>
     *
     * @return string
     */
    public function getPatternName()
    {
        return $this->pattern_name;
    }

    /**
     * Generated from protobuf field <code>string pattern_name = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setPatternName($var)
    {
        GPBUtil::checkString($var, true);
        $this->pattern_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model_external_id = 3;</code>
     *
     * @return string
     */
    public function getModelExternalId()
    {
        return $this->model_external_id;
    }

    /**
     * Generated from protobuf field <code>string model_external_id = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setModelExternalId($var)
    {
        GPBUtil::checkString($var, true);
        $this->model_external_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model_name = 4;</code>
     *
     * @return string
     */
    public function getModelName()
    {
        return $this->model_name;
    }

    /**
     * Generated from protobuf field <code>string model_name = 4;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setModelName($var)
    {
        GPBUtil::checkString($var, true);
        $this->model_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 5;</code>
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 5;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     *
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, true);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, double> measure_refs = 7;</code>
     *
     * @return MapField
     */
    public function getMeasureRefs()
    {
        return $this->measure_refs;
    }

    /**
     * Generated from protobuf field <code>map<string, double> measure_refs = 7;</code>
     *
     * @param  array|MapField  $var
     * @return $this
     */
    public function setMeasureRefs($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::DOUBLE);
        $this->measure_refs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.ChangelogEntry changelogs = 8;</code>
     *
     * @return RepeatedField
     */
    public function getChangelogs()
    {
        return $this->changelogs;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.ChangelogEntry changelogs = 8;</code>
     *
     * @param  array<ChangelogEntry>|RepeatedField  $var
     * @return $this
     */
    public function setChangelogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ChangelogEntry::class);
        $this->changelogs = $arr;

        return $this;
    }
}
