<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.PatternAnchor</code>
 */
class PatternAnchor extends Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Generated from protobuf field <code>.editor.Point2D position = 2;</code>
     */
    protected $position = null;

    /**
     * Generated from protobuf field <code>string measure_type_id = 3;</code>
     */
    protected $measure_type_id = '';

    /**
     * Generated from protobuf field <code>string role = 4;</code>
     */
    protected $role = '';

    /**
     * Generated from protobuf field <code>double measure_value = 5;</code>
     */
    protected $measure_value = 0.0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $id
     * @type \Editor\Point2D $position
     * @type string $measure_type_id
     * @type string $role
     * @type float $measure_value
     *             }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.Point2D position = 2;</code>
     *
     * @return Point2D|null
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function hasPosition()
    {
        return isset($this->position);
    }

    public function clearPosition()
    {
        unset($this->position);
    }

    /**
     * Generated from protobuf field <code>.editor.Point2D position = 2;</code>
     *
     * @param  Point2D  $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, Point2D::class);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string measure_type_id = 3;</code>
     *
     * @return string
     */
    public function getMeasureTypeId()
    {
        return $this->measure_type_id;
    }

    /**
     * Generated from protobuf field <code>string measure_type_id = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setMeasureTypeId($var)
    {
        GPBUtil::checkString($var, true);
        $this->measure_type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string role = 4;</code>
     *
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>string role = 4;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, true);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double measure_value = 5;</code>
     *
     * @return float
     */
    public function getMeasureValue()
    {
        return $this->measure_value;
    }

    /**
     * Generated from protobuf field <code>double measure_value = 5;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setMeasureValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->measure_value = $var;

        return $this;
    }
}
