<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.StrokeStyle</code>
 */
class StrokeStyle extends Message
{
    /**
     * Generated from protobuf field <code>.editor.Color stroke_color = 1;</code>
     */
    protected $stroke_color = null;

    /**
     * Generated from protobuf field <code>optional .editor.Color fill_color = 2;</code>
     */
    protected $fill_color = null;

    /**
     * Generated from protobuf field <code>double stroke_width = 3;</code>
     */
    protected $stroke_width = 0.0;

    /**
     * Generated from protobuf field <code>double opacity = 4;</code>
     */
    protected $opacity = 0.0;

    /**
     * Generated from protobuf field <code>double font_size = 5;</code>
     */
    protected $font_size = 0.0;

    /**
     * Generated from protobuf field <code>string font_family = 6;</code>
     */
    protected $font_family = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type \Editor\Color $stroke_color
     * @type \Editor\Color $fill_color
     * @type float $stroke_width
     * @type float $opacity
     * @type float $font_size
     * @type string $font_family
     *              }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.editor.Color stroke_color = 1;</code>
     *
     * @return Color|null
     */
    public function getStrokeColor()
    {
        return $this->stroke_color;
    }

    public function hasStrokeColor()
    {
        return isset($this->stroke_color);
    }

    public function clearStrokeColor()
    {
        unset($this->stroke_color);
    }

    /**
     * Generated from protobuf field <code>.editor.Color stroke_color = 1;</code>
     *
     * @param  Color  $var
     * @return $this
     */
    public function setStrokeColor($var)
    {
        GPBUtil::checkMessage($var, Color::class);
        $this->stroke_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .editor.Color fill_color = 2;</code>
     *
     * @return Color|null
     */
    public function getFillColor()
    {
        return $this->fill_color;
    }

    public function hasFillColor()
    {
        return isset($this->fill_color);
    }

    public function clearFillColor()
    {
        unset($this->fill_color);
    }

    /**
     * Generated from protobuf field <code>optional .editor.Color fill_color = 2;</code>
     *
     * @param  Color  $var
     * @return $this
     */
    public function setFillColor($var)
    {
        GPBUtil::checkMessage($var, Color::class);
        $this->fill_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double stroke_width = 3;</code>
     *
     * @return float
     */
    public function getStrokeWidth()
    {
        return $this->stroke_width;
    }

    /**
     * Generated from protobuf field <code>double stroke_width = 3;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setStrokeWidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->stroke_width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double opacity = 4;</code>
     *
     * @return float
     */
    public function getOpacity()
    {
        return $this->opacity;
    }

    /**
     * Generated from protobuf field <code>double opacity = 4;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setOpacity($var)
    {
        GPBUtil::checkDouble($var);
        $this->opacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double font_size = 5;</code>
     *
     * @return float
     */
    public function getFontSize()
    {
        return $this->font_size;
    }

    /**
     * Generated from protobuf field <code>double font_size = 5;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setFontSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->font_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string font_family = 6;</code>
     *
     * @return string
     */
    public function getFontFamily()
    {
        return $this->font_family;
    }

    /**
     * Generated from protobuf field <code>string font_family = 6;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setFontFamily($var)
    {
        GPBUtil::checkString($var, true);
        $this->font_family = $var;

        return $this;
    }
}
