<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.Transform</code>
 */
class Transform extends Message
{
    /**
     * Generated from protobuf field <code>double translate_x = 1;</code>
     */
    protected $translate_x = 0.0;

    /**
     * Generated from protobuf field <code>double translate_y = 2;</code>
     */
    protected $translate_y = 0.0;

    /**
     * Generated from protobuf field <code>double rotation = 3;</code>
     */
    protected $rotation = 0.0;

    /**
     * Generated from protobuf field <code>double scale_x = 4;</code>
     */
    protected $scale_x = 0.0;

    /**
     * Generated from protobuf field <code>double scale_y = 5;</code>
     */
    protected $scale_y = 0.0;

    /**
     * Generated from protobuf field <code>bool normalized = 6;</code>
     */
    protected $normalized = false;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type float $translate_x
     * @type float $translate_y
     * @type float $rotation
     * @type float $scale_x
     * @type float $scale_y
     * @type bool $normalized
     *            }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double translate_x = 1;</code>
     *
     * @return float
     */
    public function getTranslateX()
    {
        return $this->translate_x;
    }

    /**
     * Generated from protobuf field <code>double translate_x = 1;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setTranslateX($var)
    {
        GPBUtil::checkDouble($var);
        $this->translate_x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double translate_y = 2;</code>
     *
     * @return float
     */
    public function getTranslateY()
    {
        return $this->translate_y;
    }

    /**
     * Generated from protobuf field <code>double translate_y = 2;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setTranslateY($var)
    {
        GPBUtil::checkDouble($var);
        $this->translate_y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rotation = 3;</code>
     *
     * @return float
     */
    public function getRotation()
    {
        return $this->rotation;
    }

    /**
     * Generated from protobuf field <code>double rotation = 3;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setRotation($var)
    {
        GPBUtil::checkDouble($var);
        $this->rotation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double scale_x = 4;</code>
     *
     * @return float
     */
    public function getScaleX()
    {
        return $this->scale_x;
    }

    /**
     * Generated from protobuf field <code>double scale_x = 4;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setScaleX($var)
    {
        GPBUtil::checkDouble($var);
        $this->scale_x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double scale_y = 5;</code>
     *
     * @return float
     */
    public function getScaleY()
    {
        return $this->scale_y;
    }

    /**
     * Generated from protobuf field <code>double scale_y = 5;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setScaleY($var)
    {
        GPBUtil::checkDouble($var);
        $this->scale_y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool normalized = 6;</code>
     *
     * @return bool
     */
    public function getNormalized()
    {
        return $this->normalized;
    }

    /**
     * Generated from protobuf field <code>bool normalized = 6;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setNormalized($var)
    {
        GPBUtil::checkBool($var);
        $this->normalized = $var;

        return $this;
    }
}
