<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: editor.proto

namespace Editor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Editor;

/**
 * Generated from protobuf message <code>editor.UnifiedNode</code>
 */
class UnifiedNode extends Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Generated from protobuf field <code>.editor.NodeType type = 2;</code>
     */
    protected $type = 0;

    /**
     * Generated from protobuf field <code>string layer_id = 3;</code>
     */
    protected $layer_id = '';

    /**
     * Generated from protobuf field <code>int32 z_index = 4;</code>
     */
    protected $z_index = 0;

    /**
     * Generated from protobuf field <code>.editor.StrokeStyle style = 5;</code>
     */
    protected $style = null;

    /**
     * Generated from protobuf field <code>.editor.Transform transform = 6;</code>
     */
    protected $transform = null;

    /**
     * Generated from protobuf field <code>repeated .editor.Point2D points = 7;</code>
     */
    private $points;

    /**
     * Generated from protobuf field <code>double width = 8;</code>
     */
    protected $width = 0.0;

    /**
     * Generated from protobuf field <code>double height = 9;</code>
     */
    protected $height = 0.0;

    /**
     * Generated from protobuf field <code>string text = 10;</code>
     */
    protected $text = '';

    /**
     * Generated from protobuf field <code>bool hidden = 11;</code>
     */
    protected $hidden = false;

    /**
     * Generated from protobuf field <code>bool locked = 12;</code>
     */
    protected $locked = false;

    /**
     * Generated from protobuf field <code>optional string name = 13;</code>
     */
    protected $name = null;

    /**
     * Generated from protobuf field <code>.editor.NodeCategory category = 14;</code>
     */
    protected $category = 0;

    /**
     * Generated from protobuf field <code>repeated .editor.PathCommand path_commands = 15;</code>
     */
    private $path_commands;

    /**
     * Generated from protobuf field <code>repeated .editor.PatternAnchor anchors = 16;</code>
     */
    private $anchors;

    /**
     * Generated from protobuf field <code>optional .editor.FabricProperties fabric = 17;</code>
     */
    protected $fabric = null;

    /**
     * Generated from protobuf field <code>bool closed = 18;</code>
     */
    protected $closed = false;

    /**
     * Generated from protobuf field <code>repeated int32 curved_segments = 19;</code>
     */
    private $curved_segments;

    /**
     * Generated from protobuf field <code>int64 created_at = 20;</code>
     */
    protected $created_at = 0;

    /**
     * Generated from protobuf field <code>int64 updated_at = 21;</code>
     */
    protected $updated_at = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $id
     * @type int $type
     * @type string $layer_id
     * @type int $z_index
     * @type \Editor\StrokeStyle $style
     * @type \Editor\Transform $transform
     * @type array<\Editor\Point2D>|\Google\Protobuf\Internal\RepeatedField $points
     * @type float $width
     * @type float $height
     * @type string $text
     * @type bool $hidden
     * @type bool $locked
     * @type string $name
     * @type int $category
     * @type array<\Editor\PathCommand>|\Google\Protobuf\Internal\RepeatedField $path_commands
     * @type array<\Editor\PatternAnchor>|\Google\Protobuf\Internal\RepeatedField $anchors
     * @type \Editor\FabricProperties $fabric
     * @type bool $closed
     * @type array<int>|\Google\Protobuf\Internal\RepeatedField $curved_segments
     * @type int|string $created_at
     * @type int|string $updated_at
     *                  }
     */
    public function __construct($data = null)
    {
        Editor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.NodeType type = 2;</code>
     *
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.editor.NodeType type = 2;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, NodeType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string layer_id = 3;</code>
     *
     * @return string
     */
    public function getLayerId()
    {
        return $this->layer_id;
    }

    /**
     * Generated from protobuf field <code>string layer_id = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setLayerId($var)
    {
        GPBUtil::checkString($var, true);
        $this->layer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 z_index = 4;</code>
     *
     * @return int
     */
    public function getZIndex()
    {
        return $this->z_index;
    }

    /**
     * Generated from protobuf field <code>int32 z_index = 4;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setZIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->z_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.StrokeStyle style = 5;</code>
     *
     * @return StrokeStyle|null
     */
    public function getStyle()
    {
        return $this->style;
    }

    public function hasStyle()
    {
        return isset($this->style);
    }

    public function clearStyle()
    {
        unset($this->style);
    }

    /**
     * Generated from protobuf field <code>.editor.StrokeStyle style = 5;</code>
     *
     * @param  StrokeStyle  $var
     * @return $this
     */
    public function setStyle($var)
    {
        GPBUtil::checkMessage($var, StrokeStyle::class);
        $this->style = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.Transform transform = 6;</code>
     *
     * @return Transform|null
     */
    public function getTransform()
    {
        return $this->transform;
    }

    public function hasTransform()
    {
        return isset($this->transform);
    }

    public function clearTransform()
    {
        unset($this->transform);
    }

    /**
     * Generated from protobuf field <code>.editor.Transform transform = 6;</code>
     *
     * @param  Transform  $var
     * @return $this
     */
    public function setTransform($var)
    {
        GPBUtil::checkMessage($var, Transform::class);
        $this->transform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.Point2D points = 7;</code>
     *
     * @return RepeatedField
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.Point2D points = 7;</code>
     *
     * @param  array<Point2D>|RepeatedField  $var
     * @return $this
     */
    public function setPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Point2D::class);
        $this->points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double width = 8;</code>
     *
     * @return float
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>double width = 8;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double height = 9;</code>
     *
     * @return float
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>double height = 9;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 10;</code>
     *
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 10;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, true);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool hidden = 11;</code>
     *
     * @return bool
     */
    public function getHidden()
    {
        return $this->hidden;
    }

    /**
     * Generated from protobuf field <code>bool hidden = 11;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setHidden($var)
    {
        GPBUtil::checkBool($var);
        $this->hidden = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool locked = 12;</code>
     *
     * @return bool
     */
    public function getLocked()
    {
        return $this->locked;
    }

    /**
     * Generated from protobuf field <code>bool locked = 12;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->locked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string name = 13;</code>
     *
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 13;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.editor.NodeCategory category = 14;</code>
     *
     * @return int
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>.editor.NodeCategory category = 14;</code>
     *
     * @param  int  $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkEnum($var, NodeCategory::class);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.PathCommand path_commands = 15;</code>
     *
     * @return RepeatedField
     */
    public function getPathCommands()
    {
        return $this->path_commands;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.PathCommand path_commands = 15;</code>
     *
     * @param  array<PathCommand>|RepeatedField  $var
     * @return $this
     */
    public function setPathCommands($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, PathCommand::class);
        $this->path_commands = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.PatternAnchor anchors = 16;</code>
     *
     * @return RepeatedField
     */
    public function getAnchors()
    {
        return $this->anchors;
    }

    /**
     * Generated from protobuf field <code>repeated .editor.PatternAnchor anchors = 16;</code>
     *
     * @param  array<PatternAnchor>|RepeatedField  $var
     * @return $this
     */
    public function setAnchors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, PatternAnchor::class);
        $this->anchors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .editor.FabricProperties fabric = 17;</code>
     *
     * @return FabricProperties|null
     */
    public function getFabric()
    {
        return $this->fabric;
    }

    public function hasFabric()
    {
        return isset($this->fabric);
    }

    public function clearFabric()
    {
        unset($this->fabric);
    }

    /**
     * Generated from protobuf field <code>optional .editor.FabricProperties fabric = 17;</code>
     *
     * @param  FabricProperties  $var
     * @return $this
     */
    public function setFabric($var)
    {
        GPBUtil::checkMessage($var, FabricProperties::class);
        $this->fabric = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool closed = 18;</code>
     *
     * @return bool
     */
    public function getClosed()
    {
        return $this->closed;
    }

    /**
     * Generated from protobuf field <code>bool closed = 18;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setClosed($var)
    {
        GPBUtil::checkBool($var);
        $this->closed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 curved_segments = 19;</code>
     *
     * @return RepeatedField
     */
    public function getCurvedSegments()
    {
        return $this->curved_segments;
    }

    /**
     * Generated from protobuf field <code>repeated int32 curved_segments = 19;</code>
     *
     * @param  array<int>|RepeatedField  $var
     * @return $this
     */
    public function setCurvedSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::INT32);
        $this->curved_segments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 20;</code>
     *
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 20;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 21;</code>
     *
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 21;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at = $var;

        return $this;
    }
}
